Update scripts to also work on Windows

diff --git a/.config/profile.d/alias b/.config/profile.d/alias
--- a/.config/profile.d/alias
+++ b/.config/profile.d/alias
@@ -26,7 +26,16 @@ alias year='date +%Y'
 # df
 alias df='df -h -x tmpfs'
 
-alias finished='if [ $? == 0 ]; then FINISHED_TITLE=Succeeded; FINISHED_ICON="/usr/share/icons/breeze/emblems/8/emblem-success.svg"; (play-success &); else FINISHED_TITLE="Failed"; FINISHED_ICON="/usr/share/icons/Yaru/256x256@2x/status/dialog-error.png"; (play-fail &); fi; notify-send --icon=${FINISHED_ICON} ${FINISHED_TITLE}'
+if [ "$(uname -o)" == "Msys" ]; then
+	alias fd='fd --path-separator //'
+	alias rg='rg --path-separator //'
+fi
+
+if [ "$(uname -o)" == "Msys" ]; then
+	alias finished='if [ $? == 0 ]; then FINISHED_TITLE=Succeeded; FINISHED_ICON="info"; (play-success &); else FINISHED_TITLE="Failed"; FINISHED_ICON="error"; (play-fail &); fi; (notify-send -i ${FINISHED_ICON} "${FINISHED_TITLE}" " " &)'
+else
+	alias finished='if [ $? == 0 ]; then FINISHED_TITLE=Succeeded; FINISHED_ICON="/usr/share/icons/breeze/emblems/8/emblem-success.svg"; (play-success &); else FINISHED_TITLE="Failed"; FINISHED_ICON="/usr/share/icons/Yaru/256x256@2x/status/dialog-error.png"; (play-fail &); fi; notify-send --icon=${FINISHED_ICON} ${FINISHED_TITLE}'
+fi;
 
 alias gdb='gdb --silent'
 alias gdba='gdb --args'
